# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/email_filter',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/email_filter',
                'lib_path': 'email_filter'},
  'syms': { 'email_filter.domain_age': { 'email_filter.domain_age.check_domain_age': ( 'domain_age.html#check_domain_age',
                                                                                       'email_filter/domain_age.py'),
                                         'email_filter.domain_age.parse_domain': ( 'domain_age.html#parse_domain',
                                                                                   'email_filter/domain_age.py')},
            'email_filter.junk_checker': { 'email_filter.junk_checker.check_domain_age': ( 'junk_checker.html#check_domain_age',
                                                                                           'email_filter/junk_checker.py'),
                                           'email_filter.junk_checker.parse_domain': ( 'junk_checker.html#parse_domain',
                                                                                       'email_filter/junk_checker.py')}}}
