# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/email_filter',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/email_filter',
                'lib_path': 'email_filter'},
  'syms': {'email_filter.core': {'email_filter.core.foo': ('core.html#foo', 'email_filter/core.py')}}}
