# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_domain_age.ipynb.

# %% auto 0
__all__ = ['parse_domain', 'check_domain_age']

# %% ../nbs/00_domain_age.ipynb 3
def parse_domain(email):
    pass

# %% ../nbs/00_domain_age.ipynb 4
def check_domain_age(domain):
    pass
